// Regenerates spec/moment-cases.json from moment itself, so the Python formatter is checked
// against the real thing Obsidian uses.  npm run moment-cases
import { writeFileSync } from "node:fs";
import moment from "moment";

const formats = ["YYYY-MM-DD", "dddd, MMMM Do YYYY", "ddd D MMM YY", "[Week] W, Q", "GGGG-[W]WW", "gggg-[w]ww",
  "DDDD DDD d E e dd", "YYYY/MM/YYYY-MM-DD", "M/D/YY h:mm A a", "HH:mm:ss"];
const dates = [];
for (let y = 2019; y <= 2031; y++) {
  for (const [m, d] of [[0, 1], [0, 2], [0, 3], [0, 4], [0, 7], [1, 29], [2, 31], [5, 15], [9, 7], [11, 28], [11, 29], [11, 30], [11, 31]]) {
    const t = moment({ year: y, month: m, date: d, hour: 7, minute: 5, second: 9 });
    if (t.isValid() && t.date() === d) dates.push(t);
  }
}
const cases = dates.flatMap((t) => formats.map((f) => ({ at: t.format("YYYY-MM-DDTHH:mm:ss"), format: f, expect: t.format(f) })));
writeFileSync(new URL("../../spec/moment-cases.json", import.meta.url), JSON.stringify({
  about: "Generated by plugin/scripts/moment-cases.mjs from moment " + moment.version + " (en locale, local time).",
  cases,
}, null, 1) + "\n");
console.log(cases.length, "cases");
